# Generated by Django 3.0.7 on 2020-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='globalIp',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='localIp',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
